import{S as l,i as c}from"./assets/vendor-8c59ed88.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const a of n.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(e){if(e.ep)return;e.ep=!0;const n=o(e);fetch(e.href,n)}})();const d=document.querySelector(".gallery");function u(r){const t=document.createDocumentFragment();r.forEach(o=>{const s=m(o);t.appendChild(s)}),d.appendChild(t)}function m(r){const t=document.createElement("div");return t.classList.add("card"),t.innerHTML=`
    <a class="gallery-link" href="${r.largeImageURL}">
      <img class="card-image" src="${r.webformatURL}" alt="${r.tags}" loading="lazy">
    </a>
    <div class="card-info">
      <p class="card-text"><b>Likes:</b> ${r.likes}</p>
      <p class="card-text"><b>Views:</b> ${r.views}</p>
      <p class="card-text"><b>Comments:</b> ${r.comments}</p>
      <p class="card-text"><b>Downloads:</b> ${r.downloads}</p>
    </div>
  `,t}const p="44479541-afd008fbdfda4a6c986ece69f";function f(r){const t="https://pixabay.com",o="/api/",s=new URLSearchParams({key:p,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0}),e=`${t}${o}?${s}`;return fetch(e).then(n=>n.json())}const g=document.querySelector(".search-form"),y=document.querySelector(".gallery"),h=document.querySelector(".search-input"),b=new l(".gallery a",{captionsData:"alt",captionDelay:250}),i=document.querySelector(".loader");i.style.display="none";g.addEventListener("submit",E);function E(r){r.preventDefault();const t=h.value.trim();if(!t){c.warning({title:"Warning!",message:"Please enter image name!",position:"topRight"});return}L(),i.style.display="block",f(t).then(o=>{if(i.style.display="none",o.hits.length===0){c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}u(o.hits),b.refresh()}).catch(o=>{console.error("Error fetching images:",o),c.error({message:"Failed to fetch images. Please try again later.",position:"topRight"})})}function L(){y.innerHTML=""}
//# sourceMappingURL=commonHelpers.js.map
